apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
data:
  init-mongo.js: |
    db = db.getSiblingDB('ecommerce');
    db.createUser({
      user: "mehdiismaaili498",
      pwd: "mongopass123",
      roles: [{ role: "readWrite", db: "ecommerce" }]
    });

