apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: bWVhZGktaXNtYWFpbGk0OTg=  # Base64 encoded 'mehdiismaaili498'
  mongo-root-password: bW9uZ29wYXNzMTIz           # Base64 encoded 'mongopass123'

